addSbtPlugin("com.jsuereth"       % "sbt-pgp"                       % "1.1.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"                   % "1.0.8")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "2.3")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.0.0-M3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.5.1-KH")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.5.1-KH")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.7")
